title: Zachary Espiritu
email: me@zacharyespiritu.com
description: I'm a high school developer looking to create. Creator of Tile, Tap, Push!, Reaction Line, and Math Battle II.
baseurl: "/2016-website" # the subpath of your site, e.g. /blog
url: "http://zacharyespiritu.com" # the base hostname & protocol for your site

twitter:
  username: ZacharyEspiritu
github_username: ZacharyEspiritu

markdown: rdiscount

timezone: America/New_York

permalink: /blog/:slug/

markdown: kramdown
theme: minima

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /project/:title/
  designs:
    output: true
    permalink: /design/:title/

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
  -
    scope:
      path: ""
      type: projects
    values:
      is_project: true
