title: Zachary Espiritu
email: me@zacharyespiritu.com
description: >-
  I'm a software engineer and lighting designer. Named one of 10Under20 @ CEWeek
  2016. Developer of Math Battle, Tile, Tap, Push!, and Reaction Line.
baseurl: ""

markdown: kramdown

sass:
  style: compressed

timezone: America/New_York

github_username: ZacharyEspiritu

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# jekyll-seo-tag options.
# Refer to https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
seo:
  name: Zachary Espiritu
  type: Person
url: http://zacharyespiritu.com
twitter:
  username: ZacharyEspiritu
social:
  name: Zachary Espiritu
  links:
    - https://www.facebook.com/zachary.espiritu
    - https://twitter.com/ZacharyEspiritu
    - https://github.com/ZacharyEspiritu
    - https://www.linkedin.com/in/zacharyespiritu/

collections:
  projects:
    output: true
    permalink: /project/:title/
  designs:
    output: true
    permalink: /design/:title/
  posts:
    output: true
    permalink: /blog/:slug/

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/social-banner.png
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
  - scope:
      path: ""
      type: projects
    values:
      is_project: true
