title: Zachary Espiritu
email: me@zacharyespiritu.com
description: >-
  I'm a computer science student.
baseurl: ""

markdown: kramdown

sass:
  style: compressed

timezone: America/New_York

github_username: ZacharyEspiritu

repository: ZacharyEspiritu/zacharyespiritu.github.io

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# jekyll-seo-tag options.
# Refer to https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
seo:
  name: Zachary Espiritu
  type: Person
url: https://zacharyespiritu.com
twitter:
  username: ZacharyEspiritu
social:
  name: Zachary Espiritu
  links:
    - https://www.facebook.com/zachary.espiritu
    - https://github.com/ZacharyEspiritu
    - https://www.linkedin.com/in/zacharyespiritu/

collections:
  projects:
    output: true
    permalink: /project/:title/
  designs:
    output: true
    permalink: /design/:title/
  notes:
    output: true
    permalink: /notes/:slug/
  experience:
    output: false
  presentations:
    output: false
  awards:
    output: false
  teaching:
    output: false
  education:
    output: false

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/social-banner.png
  - scope:
      path: ""
      type: notes
    values:
      is_note: true
  - scope:
      path: ""
      type: projects
    values:
      is_project: true
  - scope:
      path: ""
      type: designs
    values:
      is_design: true
